targets:
  $default:
    builders:
      brick_offline_first_with_supabase_build:
        generate_for:
          - lib/features/catalog/domain/*.dart
        options:
          export:
            - lib/brick/brick.g.dart
