#!/bin/bash
# =============================================================================
# 🤖 AI Agent Orchestrator — Example Script
# =============================================================================
# This script demonstrates how to invoke each AI agent in sequence.
# In practice, this is handled by the GitHub Actions workflow with approval gates.
#
# Usage: ./scripts/orchestrate.sh "feature description"
# =============================================================================

set -e

FEATURE_DESCRIPTION="$1"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
OUTPUT_DIR="./agent_outputs/${TIMESTAMP}"

if [ -z "$FEATURE_DESCRIPTION" ]; then
  echo "❌ Error: Please provide a feature description"
  echo "Usage: ./scripts/orchestrate.sh \"Your feature description\""
  exit 1
fi

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          🤖 AI Multi-Agent Pipeline Orchestrator            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📝 Feature: $FEATURE_DESCRIPTION"
echo "📁 Output: $OUTPUT_DIR"
echo ""

mkdir -p "$OUTPUT_DIR"

# =============================================================================
# Stage 1: Product Manager
# =============================================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔵 Stage 1: Product Manager Agent"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Generating user stories for: $FEATURE_DESCRIPTION"
echo ""

cat > "$OUTPUT_DIR/01_user_stories.md" << EOF
# User Stories — Generated by PM Agent

## Feature: $FEATURE_DESCRIPTION

### Story 1
AS A collector
I WANT TO [action based on feature]
SO THAT [benefit]

**Acceptance Criteria:**
- Given [precondition]
- When [action]
- Then [result]

---
*Generated at: $(date)*
*Status: ⏳ Awaiting orchestrator approval*
EOF

echo "✅ User stories generated: $OUTPUT_DIR/01_user_stories.md"
echo ""
echo "🟣 ORCHESTRATOR ACTION REQUIRED:"
echo "   Review the stories and type 'approve' or 'reject [reason]'"
read -p "   > " PM_DECISION

if [[ "$PM_DECISION" != "approve" ]]; then
  echo "❌ Stories rejected. Reason: $PM_DECISION"
  echo "🔄 Re-running PM Agent with feedback..."
  exit 0
fi

echo "✅ Stories approved! Proceeding to Backend Agent..."
echo ""

# =============================================================================
# Stage 2: Backend Developer
# =============================================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟢 Stage 2: Backend Developer Agent"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

cat > "$OUTPUT_DIR/02_migration.sql" << EOF
-- Migration: ${TIMESTAMP}_feature.sql
-- Feature: $FEATURE_DESCRIPTION
-- Generated by: Backend Developer Agent

CREATE TABLE IF NOT EXISTS new_feature (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE new_feature ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own data" ON new_feature
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own data" ON new_feature
    FOR INSERT WITH CHECK (auth.uid() = user_id);
EOF

echo "✅ Migration generated: $OUTPUT_DIR/02_migration.sql"
echo ""
echo "🟣 ORCHESTRATOR ACTION REQUIRED:"
echo "   Review the migration and type 'approve' or 'reject [reason]'"
read -p "   > " BE_DECISION

if [[ "$BE_DECISION" != "approve" ]]; then
  echo "❌ Backend rejected. Re-running..."
  exit 0
fi

echo "✅ Backend approved! Proceeding to Frontend Agent..."
echo ""

# =============================================================================
# Stage 3: Frontend Developer
# =============================================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟡 Stage 3: Frontend Developer Agent"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Generating Flutter code based on approved stories and schema..."
echo "✅ Brick models generated"
echo "✅ Riverpod providers generated"
echo "✅ UI screens generated"
echo "✅ Tests generated"
echo ""
echo "🟣 ORCHESTRATOR ACTION REQUIRED:"
echo "   Review the Flutter code and type 'approve' or 'reject [reason]'"
read -p "   > " FE_DECISION

if [[ "$FE_DECISION" != "approve" ]]; then
  echo "❌ Frontend rejected. Re-running..."
  exit 0
fi

# =============================================================================
# Stage 4 & 5: DevOps + QA (Automatic)
# =============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔴 Stage 4: DevOps Agent (Automatic)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ CI/CD configuration verified"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🟣 Stage 5: QA Agent — Running Quality Analysis"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🔎 Flutter Analyze.......... ✅ PASS"
echo "  🧪 Unit Tests............... ✅ PASS (42/42)"
echo "  📊 Coverage................. ✅ 87%"
echo "  🔒 SonarQube Scan.......... ✅ 0 vulnerabilities"
echo "  🏁 Quality Gate............. ✅ PASSED"
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║              ✅ PIPELINE COMPLETE — READY TO MERGE           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "📁 All outputs saved in: $OUTPUT_DIR"
echo "🚀 Run 'git merge' to deploy the feature!"
